### ISSUE TITLE
Cannot GET / 

### ISSUE THREAD

**Issue by andrewclaus** [auth0-samples/auth0-angular-samples#256]
Hello, I am trying to build the first sample project on a **Mac**, but I am unable to load the webpage, I only get "Cannot GET /"

The steps I have followed:

1. Installed npm with `brew install npm`
2. I believe I have updated auth_config.json with the correct tenant values
3. Ran `npm run dev` and waited for it to say ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
4. Navigated to `http://localhost:4200/`
5. The page is blank except for `Cannot GET /`

I also tried building and running the docker image, but that has the same result.

<details>
  <summary>Full output from running `npm run dev`, including some css dependency errors that I am not sure if it is related to my problem:</summary>
 
> login-demo@0.0.0 dev
> npm-run-all --parallel start server:api

> login-demo@0.0.0 server:api
> node api-server.js

> login-demo@0.0.0 start
> ng serve

Api started on port 3001
✔ Browser application bundle generation complete.

Initial Chunk Files                | Names                           |    Size
main.js                            | main                            | 0 bytes
polyfills.js                       | polyfills                       | 0 bytes
runtime.js                         | runtime                         | 0 bytes
styles.js                          | styles                          | 0 bytes
vendor.js                          | vendor                          | 0 bytes

                                   | Initial Total                   | 0 bytes

Lazy Chunk Files                   | Names                           |    Size
highlight-js-lib-core.js           | highlight-js-lib-core           | 0 bytes
highlight-js-lib-languages-json.js | highlight-js-lib-languages-json | 0 bytes

Build at: 2022-02-09T04:00:51.527Z - Hash: b161130827efb348fa4b - Time: 8037ms

Error: ./src/styles.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/AClaus/Downloads/sample-01 2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/AClaus/Downloads/sample-01 2/node_modules/css-loader/dist/index.js:12:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/AClaus/Downloads/sample-01 2/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/AClaus/Downloads/sample-01 2/node_modules/loader-runner/lib/LoaderRunner.js:172:11
    at loadLoader (/Users/AClaus/Downloads/sample-01 2/node_modules/loader-runner/lib/loadLoader.js:32:11)
    at iteratePitchingLoaders (/Users/AClaus/Downloads/sample-01 2/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/AClaus/Downloads/sample-01 2/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/Compilation.js:739:10)
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/Compilation.js:1111:12
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModuleFactory.js:409:6
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/AClaus/Downloads/sample-01 2/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/AClaus/Downloads/sample-01 2/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModuleFactory.js:138:29
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModuleFactory.js:346:9

Error: ./node_modules/highlight.js/styles/monokai-sublime.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/AClaus/Downloads/sample-01 2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/AClaus/Downloads/sample-01 2/node_modules/css-loader/dist/index.js:12:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/AClaus/Downloads/sample-01 2/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/AClaus/Downloads/sample-01 2/node_modules/loader-runner/lib/LoaderRunner.js:172:11
    at loadLoader (/Users/AClaus/Downloads/sample-01 2/node_modules/loader-runner/lib/loadLoader.js:32:11)
    at iteratePitchingLoaders (/Users/AClaus/Downloads/sample-01 2/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/AClaus/Downloads/sample-01 2/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/Compilation.js:739:10)
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/Compilation.js:1111:12
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModuleFactory.js:409:6
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/AClaus/Downloads/sample-01 2/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/AClaus/Downloads/sample-01 2/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModuleFactory.js:138:29
    at /Users/AClaus/Downloads/sample-01 2/node_modules/webpack/lib/NormalModuleFactory.js:346:9

Error: ./src/app/app.component.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/AClaus/Downloads/sample-01 2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/AClaus/Downloads/sample-01 2/node_modules/postcss-loader/dist/index.js:16:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Error: ./src/app/pages/home/home.component.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/AClaus/Downloads/sample-01 2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/AClaus/Downloads/sample-01 2/node_modules/postcss-loader/dist/index.js:16:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Error: ./src/app/pages/profile/profile.component.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/AClaus/Downloads/sample-01 2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/AClaus/Downloads/sample-01 2/node_modules/postcss-loader/dist/index.js:16:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Error: ./src/app/pages/external-api/external-api.component.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/AClaus/Downloads/sample-01 2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/AClaus/Downloads/sample-01 2/node_modules/postcss-loader/dist/index.js:16:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Error: ./src/app/components/nav-bar/nav-bar.component.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/AClaus/Downloads/sample-01 2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/AClaus/Downloads/sample-01 2/node_modules/postcss-loader/dist/index.js:16:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Error: ./src/app/components/footer/footer.component.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/AClaus/Downloads/sample-01 2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)m
    at Object.<anonymous> (/Users/AClaus/Downloads/sample-01 2/node_modules/postcss-loader/dist/index.js:16:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Error: ./src/app/components/hero/hero.component.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/AClaus/Downloads/sample-01 2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/AClaus/Downloads/sample-01 2/node_modules/postcss-loader/dist/index.js:16:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Error: ./src/app/components/home-content/home-content.component.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/AClaus/Downloads/sample-01 2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/AClaus/Downloads/sample-01 2/node_modules/postcss-loader/dist/index.js:16:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
[91m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Error: ./src/app/components/loading/loading.component.css
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/AClaus/Downloads/sample-01 2/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/AClaus/Downloads/sample-01 2/node_modules/postcss-loader/dist/index.js:16:39)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
</details>

I am running on a private Auth0 cloud instance, do I need to set some additional configuration because of that?

**Comment by frederikprijck** [comment]
Hey,

Looking at the errors, it seems like none of them relate to our SDK. Would you be able to share a reproduction if you believe our SDK is causing this?

Thanks

**Comment by andrewclaus** [comment]
Thanks for taking a look. It could very well be because I am on a Mac or because this is the first time I am using these tools. Is someone on your end with a Mac able to validate the steps I followed?
