### ISSUE TITLE
Invalid state error from handleRedirectCallback function

### ISSUE THREAD

**Issue by lukaszkorona** [auth0-samples/auth0-angular-samples#371]
Hi,
We keep getting Invalid State error from handleRedirectCallback function after successful login redirect. State and code parameters are always present 

Our module is configured in following way:
AuthModule.forRoot({
            domain: environment.auth.domain,
            clientId: environment.auth.clientID,
            authorizationParams: {
                redirect_uri: environment.auth.redirect,
                audience: environment.auth.audience,
                scope: 'openid profile email offline_access',
              },
            useRefreshTokens: true,
            useRefreshTokensFallback: true,
            
            // The AuthHttpInterceptor configuration https://auth0.com/docs/libraries/auth0-angular-spa#configure-the-http-interceptor
            httpInterceptor: {
                allowedList: [ 
                    'https://apitest.taalhammer.com/*',
            ]}
        }

with params:
 auth: {
        clientID: 'N2NLkUmiRFIquVAcrg978ElNdZtiAf4V',
        domain: 'th-dev.eu.auth0.com',
        audience: 'https://apitest.taalhammer.com/',
        redirect: 'http://localhost:4200/callback',
        scope: 'openid profile email',
        returnToAfterLogout: 'https://wptest.taalhammer.com/wp-login.php?action=logout',
        landingPage: 'https://wptest.taalhammer.com',
        loginURL: 'https://wptest.taalhammer.com/login'
    }

inside callback we simply try to call handleRedirectCallback function
this.auth.handleRedirectCallback().subscribe(result => {

package versions:
    "@auth0/auth0-angular": "^2.1.0",
    "@auth0/auth0-spa-js": "^1.13.1",

error:
Error: Invalid state
    at auth0-spa-js.production.esm.js:1:31028
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
    at asyncToGenerator.js:32:1
    at new ZoneAwarePromise (zone.js:1340:33)
    at asyncToGenerator.js:21:1
    at te.handleRedirectCallback (auth0-spa-js.production.esm.js:1:30578)
    at auth0-auth0-angular.mjs:441:45
    at Observable._subscribe (defer.js:8:21)
    at Observable._trySubscribe (Observable.js:42:25)
    at Observable.subscribe (Observable.js:28:22)
    at WithLatestFromOperator.call (withLatestFrom.js:19:23)
    at Observable.subscribe (Observable.js:23:31)
    at DoOperator.call (tap.js:16:23)

**Comment by frederikprijck** [comment]
Thanks for reaching out. Hard to tell what's going on. Can you reproduce the issue in the sample application?

Can you elaborate on why you are using Auth0-SPA-JS v1 together with Auth0-Angular v2?

**Comment by frederikprijck** [comment]
Closing due to inactivity. Feel free to ping me and we can reopen.

**Comment by lukaszkorona** [comment]
Hi,
We get the same issue in the sample application and in the sample application we only used "@auth0/auth0-angular": "^2.1.0" and we got the same error. 
We've been also in touch with Auth0 support and the suggestion was that potentialy handleRedirectCallback should not be called explicitly  because most probably it is called explicitly becase we import it in the main module.
Is it really the case? We got confused. So what is the usecase for calling handleRedirectCallback?

**Comment by frederikprijck** [comment]
Using handleRedirectCallback is mostly to integrate with capacitor's browser. 

What's the reason you are calling it yourself?

**Comment by lukaszkorona** [comment]
So we're in the middle od Ionic/capacitor app implementation. We initially understood that it is also security best practice to call it inside callback component of Angular SPA.
So for Angular app we don't have to do anything in terms of handleRedirectCallback and for the capacitor app we should still call it explicitly after redirect from authorisation server?

**Comment by frederikprijck** [comment]
Yes, that should be correct. With Capacitor, you want to use the browser plugin and integrate the SDK as mentioned here: https://auth0.com/docs/quickstart/native/ionic-angular
